
metadatum <- function(class = "character",
                      permitted_values) {
  defined <- ls()
  passed <- names(as.list(match.call())[-1])

  if (any(!defined %in% passed)) {
    stop(paste("missing values for",
               paste(setdiff(defined, passed),
                     collapse = ", ")))
  }

  list(class = class,
       permitted_value = permitted_values)
}

metadatum_logical <- function(has_na) {
  if (is.na(has_na)) {
    metadatum(class = "logical",
              permitted_values = c(NA, FALSE, TRUE))
  } else {
    metadatum(class = "logical",
              permitted_values = c(FALSE, TRUE))
  }
}



MEASURE_VARS <-
  list("Age" = metadatum(class = c("ordered", "factor"),
                         permitted_values = c("0-4", "5-14",
                                              "15-19", "20-24", "25-34",
                                              "35-44", "45-54", "55-64",
                                              "65-74",
                                              "75+",
                                              "75-84",
                                              "85+")),
       "Age.min" = metadatum(class = "integer",
                             permitted_values = 0:100),
       "AgeStudent" = metadatum(class = c("ordered", "factor"),
                                permitted_values = c("0-4", "5-14", "15-19", "20-24", "25+")),
       "AgedUnder25" = metadatum_logical(NA),
       "Ancestry" = metadatum(class = "character",
                              permitted_values = c(NA, "Australian", "Australian Aboriginal",
                                                   "Chinese", "Croatian",
                                                   "Dutch", "English", "Filipino", "French",
                                                   "German", "Greek",
                                                   "Hungarian", "Indian", "Irish", "Italian",
                                                   "Korean", "Lebanese",
                                                   "Macedonian", "Maltese", "Maori", "NZ",
                                                   "(Other)", "Polish",
                                                   "Russian", "Scottish", "Serbian",
                                                   "South African", "Spanish",
                                                   "Sri Lankan", "Turkish", "Vietnamese",
                                                   "Welsh")),
       "AustCitizen" = metadatum_logical(),
       "BornAust" = metadatum_logical(),
       "ChildrenEverBorn" = metadatum(class = "integer",
                                      permitted_values = c(NA, 0:6)),
       "ChildrenPresent" = metadatum_logical(),
       "CountryOfBirth" = function(x) {
         is.character(x) && all(nchar(x) == 3L)
       },
       "CoupleFamily" = metadatum_logical(NA),
       "Denomination" = metadatum(class = "character",
                                  permitted_values = c(NA, "(Other)", "Australian Aboriginal Traditional", "Other spiritual beliefs",
                                                       "Secular beliefs", "Sikhism", "Anglican", "Assyrian Apostolic", "Baptist",
                                                       "Brethren", "Catholic", "Church Christ", "Eastern Orthodox",
                                                       "Jehovah's Witnesses", "Latter Day Saints", "Lutheran", "Oriental Orthodox",
                                                       "Pentecostal", "Presbyterian Reformed", "Protestant (Other)",
                                                       "Salvation Army", "Seventh Day Adventist", "Uniting Church")),
       "Dwelling" = function(x) stop("Dwelling not a permitted name"),
       "PrivateDwelling" = metadatum_logical(),
       "DwellingStructure" = metadatum(class = "character",
                                       permitted_values = c(NA,
                                                            "(Other)",
                                                            "Flat/apartment",
                                                            "Semi-detached, row/terrace house, townhouse etc.",
                                                            "Separate house")),
       "DwellingSubtype" = metadatum(class = "character",
                                     permitted_values = c(NA, "Cabin household", "Caravan",
                                                          "House or flat attached to a shop, office, etc",
                                                          "Improvised home, tent sleepers",
                                                          "1 or 2 storey block", "3 storey block",
                                                          "4 storey block or more",
                                                          "Attached to a house", "1 storey")),
       "EduInstitutionType" = metadatum(class = "character",
                                        permitted_values = c(NA, "(Other)", "Infants/Primary",
                                                             "Pre-school", "Secondary",
                                                             "Technical or Further Educational Institution",
                                                             "University or other tertiary")),
       "EnglishProficiency" = metadatum(class = c("ordered", "factor"),
                                        permitted_values = c(NA,
                                                            "Speaks English well or very well",
                                                            "Speaks English not well or not at all")),
       "FamilyComposition" = metadatum(permitted_values = c("Blended family with no other children present",
                                                            "Blended family with other children present",
                                                            "Intact family with no other children present",
                                                            "Intact family with other children present",
                                                            "Other couple family with other children only",
                                                            "Step family with no other children present",
                                                            "Step family with other children present")),
       "FamilyHousehold" = metadatum_logical(),
       "FatherBornAus" = metadatum_logical(),
       "ForOtherChild" = metadatum_logical(),
       "ForOwnChild" = metadatum_logical(),
       "FullTime" = metadatum_logical(),
       "HasChild" = metadatum_logical(),
       "HasChildren" = function(x) stop("Use HasChild."),
       "HasChildUnder15" = metadatum_logical(),
       "HasChildrenUnder15" = function(x) stop("Use HasChildUnder15."),
       "HasDependentStudent" = metadatum_logical(),
       "HasNonDependentChild" = metadatum_logical(),
       "HomeCensusNight" = metadatum_logical(),
       "HoursHousekeeping" = metadatum(class = c("ordered", "factor"),
                                       permitted_values = c("0", "<5", "5-14",
                                                            "15-29", "30+")),
       "IncomeFamily.max" = metadatum(class = "double",
                                      permitted_values = c(NA, 0, 7875, 15750, 21000, 26250, 34125, 42000, 52500, 65625,
                                                           78750, 91875, 105000, 131250, 157500, 183750, 210000, Inf)),
       "IncomeHousehold.max"  = metadatum(class = "double",
                                          permitted_values = c(NA, 0, 7875, 15750, 21000, 26250, 34125, 42000, 52500, 65625,
                                                               78750, 91875, 105000, 131250, 157500, 183750, 210000, Inf)),
       "IncomeTotPersonal.max" = metadatum(class = "double",
                                           permitted_values = c(NA, 0, 7875, 15750, 21000, 26250, 34125, 42000, 52500, 65625,
                                                                78750, 91875, 105000, 131250, 157500, 183750, 210000, Inf)),
       "IncomeTotPersonal.min" = function(x) stop("Don't use."),
       "Indigenous" = metadatum_logical(),
       "IndigenousStatus" = metadatum(class = "factor",
                                      permitted_values = c("Aboriginal", "Torres Strait Islander",
                                                           "Both Aboriginal & Torres Strait Islander", "Non-indigenous")),
       "InternetAccessedFromDwelling" = metadatum_logical(NA),
       "Landlord" = metadatum(class = "character",
                              permitted_values = c(NA, "(Other)", "Co-op/church group etc", "Person not in same household",
                                                   "Real estate agent", "State or territory housing authority")),
       "MaritalStatus" = metadatum(permitted_values = c("Married", "Not married", "Divorced", "Separated", "Widowed")),
       "MaxSchoolingCompleted" = metadatum(class = c("ordered", "factor"),
                                           permitted_values = c("Did not go to school",
                                                                "Year 8 or below",
                                                                "Year 8",
                                                                "Year 9",
                                                                "Year 10",
                                                                "Year 11",
                                                                "Year 12")),
       "MortgageRepayment.min" = metadatum(class = "integer",
                                           permitted_values = c(0L, 1800L, 3600L, 5400L, 7200L, 9600L, 12000L, 14400L, 16800L,
                                                                19200L, 21600L, 24000L, 26400L, 28800L, 31200L, 36000L, 48000L,
                                                                60000L)),
       "MotherBornAus" = metadatum_logical(),
       "MotorVehicles.min" = metadatum(class = "integer",
                                       permitted_values = c(NA, 0L, 1L, 2L, 3L, 4L)),
       "NeedsAssistance" = metadatum_logical(NA),
       "NumberBedrooms.min" = metadatum(class = "integer",
                                        permitted_values = c(NA, 0L, 1L, 2L, 3L, 4L, 5L, 6L)),
       "OnlyEnglishSpokenHome" = metadatum_logical(),
       "ParentsBornAus" = metadatum(class = "character",
                                    permitted_values = c(NA, "Both", "Father only", "Mother only", "Neither")),
       "ProvidedUnpaidChildcare" = metadatum_logical(NA),
       "ProvidedUnpaidDisabilityAssistance"= metadatum_logical(NA),
       "Registered"= metadatum_logical(NA),
       "Religion" = metadatum(class = "character",
                              permitted_values = c("(Other)", "Buddhism", "Christianity", "Hinduism", "Islam",
                                                   "Judaism", "No religion")),
       "Rent.min" = metadatum(class = "integer",
                              permitted_values = c(0L, 3937L, 5250L, 7875L, 10500L, 11812L, 14437L, 18375L, 23625L,
                                                   28875L, 34125L, 39375L, 44625L, 49875L)),
       "SchoolSector" = metadatum(class = "character",
                                  permitted_values = c(NA, "Catholic", "Government", "Non-government")),
       "Sex" = metadatum(class = "character", permitted_values = c("M", "F")),
       "SpeaksEnglishOnly" = metadatum_logical(NA),
       "UsualResidence" = metadatum(class = "character",
                                    permitted_values = c("Home",
                                                         "Visitor same SA2",
                                                         "Visitor from ACT",
                                                         "Visitor from NSW",
                                                         "Visitor from NT",
                                                         "Visitor from OT",
                                                         "Visitor from QLD",
                                                         "Visitor from SA",
                                                         "Visitor from TAS",
                                                         "Visitor from VIC",
                                                         "Visitor from WA")),
       "UsualResidents.min" = metadatum(class = "integer",
                                        permitted_values = 1:6),
       "Volunteer" = metadatum_logical(NA),
       "YearOfArrival.max" = metadatum(class = "integer",
                                       permitted_values = c(NA, 2005L, 2010L, 2011L, 2012L, 2013L, 2014L, 2015L, 2016L,
                                                            2000L, 1946L, 1955L, 1965L, 1975L, 1985L, 1995L, 2005L, 2010L, 1955L,
                                                            1965L, 1975L, 1985L, 1995L)),
       "medianMortgageRepayment" = is.integer,
       "medianRent" = is.integer,
       "medianTotalFamilyIncome" = is.integer,
       "medianTotalHouseholdIncome" = is.integer,
       "medianTotalPersonalIncome" = is.integer)
